### ISSUE TITLE
How to process the NSD Dataset? 

### ISSUE THREAD

**Issue by arnoliudaxia** [Gabesarch/brain-dissection#1]
I have already download the NSD dataset, what else should I do to reproduce your results?
For example, may you provide a script that generates the "averaged_cortical_responses_zscored_by_run_subj%02d.npy" file which is used in  `backend/dataloaders/nsd_response_loader.py:60` ?

**Comment by Gabesarch** [comment]
Sorry for the confusion. I've added a new script [here](https://github.com/Gabesarch/brain-dissection/blob/main/process_nsd.sh) with NSD pre-processing steps.
